name: Verify

env:
  go-version: '1.18.2'

# Trigger the workflow on all pull requests, and on push to specific branches
on:
  # run for all pull requests and pushes to certain branches
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      # Preparing env
      - name: Install Node.js, NPM
        if: ${{ steps.result.outputs.status != 'success' }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: checkout
        uses: actions/checkout@v2
      # Creating release
      - name: build release notes
        id: notes
        run: |
          BODY=$(./gen-notes.js)
          echo "::set-output name=body::${BODY}"
      - name: Post notes to PR
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: ${{ steps.notes.outputs.body }}