name: Create Release draft

on:
  push:
    tags:
    - '*'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      # Preparing env
      - name: Install Node.js, NPM
        if: ${{ steps.result.outputs.status != 'success' }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: checkout
        uses: actions/checkout@v2
      # Load tag
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      # Load release data
      - name: load JSON
        id: json
        run: |
          content=`cat ./release.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=json::$content"
      # Ensure that tag and version in `release.yml` are equal
      - name: Tag and Network Id are equals
        if: ${{ steps.tagName.outputs.tag != fromJson(steps.json.outputs.json).id }}
        run: |
          echo "Tag does not match Network Id."
          echo "Tag: ${{ steps.tagName.outputs.tag }}"
          echo "Network Id: ${{ fromJson(steps.json.outputs.json).id }}"
          exit 1
      # Creating release
      - name: build release notes
        id: notes
        run: ./gen-notes.js > ./RELEASE.md
      - name: Create Release draft
        id: create-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ fromJson(steps.json.outputs.json).name }}
          body_path: ./RELEASE.md
          draft: true
          prerelease: true