name: Publish network

env:
  go-version: '1.18.2'

# Trigger the workflow on all pull requests, and on push to specific branches
on:
  # run for all pull requests and pushes to certain branches
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Preparing env
      - name: Install Node.js, NPM
        if: ${{ steps.result.outputs.status != 'success' }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: checkout
        uses: actions/checkout@v2
      # Creating release
      - name: build release notes
        id: notes
        run: |
          BODY=$(./gen-notes.js)
          echo "::set-output name=body::${BODY}"
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ fromJson('./release.json').id }}
      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ fromJson('./release.json').id }}
          body: ${{ steps.notes.outputs.body }}
          draft: false
          prerelease: false